import type { BrandEntry } from "./index.ts";

export const genericBrands: BrandEntry[] = [
  { patterns: ["SAMSUNG"], name: "Samsung", origin: "global" },
  { patterns: ["APPLE"], name: "Apple", origin: "global" },
  { patterns: ["XIAOMI"], name: "Xiaomi", origin: "global" },
  { patterns: ["SONY"], name: "Sony", origin: "global" },
  { patterns: ["LG"], name: "LG", origin: "global" },
  { patterns: ["PHILIPS"], name: "Philips", origin: "global" },
  { patterns: ["PANASONIC"], name: "Panasonic", origin: "global" },
  { patterns: ["JBL"], name: "JBL", origin: "global" },
  { patterns: ["BOSE"], name: "Bose", origin: "global" },
  { patterns: ["ANKER"], name: "Anker", origin: "global" },
  { patterns: ["BASEUS"], name: "Baseus", origin: "global" },
  { patterns: ["LOGITECH"], name: "Logitech", origin: "global" },
  { patterns: ["DELL"], name: "Dell", origin: "global" },
  { patterns: ["HP", "HEWLETT"], name: "HP", origin: "global" },
  { patterns: ["LENOVO"], name: "Lenovo", origin: "global" },
  { patterns: ["ASUS"], name: "Asus", origin: "global" },
  { patterns: ["ACER"], name: "Acer", origin: "global" },
  { patterns: ["MICROSOFT"], name: "Microsoft", origin: "global" },
  { patterns: ["GOOGLE"], name: "Google", origin: "global" },
  { patterns: ["HUAWEI"], name: "Huawei", origin: "global" },
  { patterns: ["OPPO"], name: "Oppo", origin: "global" },
  { patterns: ["REALME"], name: "Realme", origin: "global" },
  { patterns: ["MOTOROLA"], name: "Motorola", origin: "global" },
  { patterns: ["NOKIA"], name: "Nokia", origin: "global" },
  { patterns: ["NINTENDO"], name: "Nintendo", origin: "global" },
  { patterns: ["DYSON"], name: "Dyson", origin: "global" },
  { patterns: ["BRAUN"], name: "Braun", origin: "global" },
  { patterns: ["ORAL-B", "ORALB"], name: "Oral-B", origin: "global" },
  { patterns: ["EPSON"], name: "Epson", origin: "global" },
  { patterns: ["CANON"], name: "Canon", origin: "global" },
  { patterns: ["NIKON"], name: "Nikon", origin: "global" },
  { patterns: ["GOPRO"], name: "GoPro", origin: "global" },
  { patterns: ["DJI"], name: "DJI", origin: "global" },
  { patterns: ["SENNHEISER"], name: "Sennheiser", origin: "global" },
  { patterns: ["HARMAN KARDON", "HARMAN"], name: "Harman Kardon", origin: "global" },
  { patterns: ["MARSHALL"], name: "Marshall", origin: "global" },
  { patterns: ["BEATS"], name: "Beats", origin: "global" },
  { patterns: ["RAZER"], name: "Razer", origin: "global" },
  { patterns: ["CORSAIR"], name: "Corsair", origin: "global" },
  { patterns: ["HYPERX"], name: "HyperX", origin: "global" },
  { patterns: ["WHIRLPOOL"], name: "Whirlpool", origin: "global" },
  { patterns: ["ELECTROLUX"], name: "Electrolux", origin: "global" },
  { patterns: ["BOSCH"], name: "Bosch", origin: "global" },
  { patterns: ["SIEMENS"], name: "Siemens", origin: "global" },
  { patterns: ["TEFAL", "T-FAL"], name: "Tefal", origin: "global" },
  { patterns: ["KITCHENAID"], name: "KitchenAid", origin: "global" },
  { patterns: ["NESPRESSO"], name: "Nespresso", origin: "global" },
  { patterns: ["DE LONGHI", "DELONGHI"], name: "De'Longhi", origin: "global" },
];
